import { prisma } from '../src/db/prisma.js'

const DISH_IMAGE = '@/assets/images/BWE1_0015_rune-stone-button-circle.png'

async function main() {
  await prisma.dish.createMany({
    data: [
      {
        name: 'Похлёбка авантюриста',
        description: 'Густой бульон с олениной, кореньями и травами из Тёмного леса. Возвращает силы после долгого похода.',
        price: 450,
        image: DISH_IMAGE,
        category: 'food',
        tags: ['spicy', 'restorative'],
      },
      {
        name: 'Жаркое "Щит и Меч"',
        description: 'Рёбрышки вепря, томлёные в эле с чесноком и розмарином. Подаётся на чугунной сковороде.',
        price: 680,
        image: DISH_IMAGE,
        category: 'food',
        tags: ['meat', 'popular'],
      },
      {
        name: 'Эльфийский салат',
        description: 'Свежая зелень, запечённая свёкла, козий сыр и грецкие орехи под медово-горчичной заправкой.',
        price: 320,
        image: DISH_IMAGE,
        category: 'food',
        tags: ['vegetarian'],
      },
      {
        name: 'Пирог дварфийский слоёный',
        description: 'Десять слоёв теста с начинкой из грибов, картофеля и копчёного мяса. Осилит не каждый.',
        price: 520,
        image: DISH_IMAGE,
        category: 'food',
        tags: ['meat', 'hearty'],
      },
      {
        name: 'Крылышки дракона',
        description: 'Острые куриные крылья в глазури из мёда и перца чили. Название — маркетинг, драконы не пострадали.',
        price: 390,
        image: DISH_IMAGE,
        category: 'food',
        tags: ['spicy', 'popular'],
      },
      {
        name: 'Уха из Зеркального озера',
        description: 'Нежный рыбный суп с лососем, сливками и шафраном. Рецепт хранится в таверне три поколения.',
        price: 550,
        image: DISH_IMAGE,
        category: 'food',
        tags: ['fish', 'restorative'],
      },
      {
        name: 'Гномий грибной рататуй',
        description: 'Подземные грибы, тушённые с тыквой и пряностями. Подаётся в хлебной миске.',
        price: 400,
        image: DISH_IMAGE,
        category: 'food',
        tags: ['vegetarian'],
      },
      {
        name: 'Баранья нога по-оркски',
        description: 'Здоровенный кусок мяса на кости, маринованный в остром соусе и запечённый на открытом огне.',
        price: 750,
        image: DISH_IMAGE,
        category: 'food',
        tags: ['meat', 'spicy', 'hearty'],
      },
      {
        name: 'Эль "Молот Торина"',
        description: 'Тёмный дварфийский эль с нотками карамели и дыма. Подаётся в литровой кружке.',
        price: 280,
        image: DISH_IMAGE,
        category: 'drink',
        tags: ['alcohol', 'popular'],
      },
      {
        name: 'Медовуха странника',
        description: 'Лёгкая медовая настойка на травах и ягодах. Согревает в пути и не туманит голову.',
        price: 250,
        image: DISH_IMAGE,
        category: 'drink',
        tags: ['alcohol'],
      },
      {
        name: 'Вино эльфийской лозы',
        description: 'Белое вино из винограда, выращенного в лунных садах. Говорят, раскрывает третий глаз.',
        price: 600,
        image: DISH_IMAGE,
        category: 'drink',
        tags: ['alcohol', 'exotic'],
      },
      {
        name: 'Грог "Северный ветер"',
        description: 'Ром с пряностями, мёдом и лимоном. Горячий. Рекомендуется после встречи с ледяными великанами.',
        price: 350,
        image: DISH_IMAGE,
        category: 'drink',
        tags: ['alcohol', 'restorative'],
      },
      {
        name: 'Чай шамана',
        description: 'Травяной сбор из десяти редких растений. Успокаивает дух и лечит мелкие раны.',
        price: 200,
        image: DISH_IMAGE,
        category: 'drink',
        tags: ['non-alcoholic', 'restorative'],
      },
      {
        name: 'Квас богатырский',
        description: 'Ядрёный ржаной квас на изюме и мяте. Освежает лучше всякого зелья.',
        price: 150,
        image: DISH_IMAGE,
        category: 'drink',
        tags: ['non-alcoholic'],
      },
      {
        name: 'Кровь врагов',
        description: 'Томатный сок с сельдереем, перцем и секретным ингредиентом. На вкус лучше, чем на слух.',
        price: 220,
        image: DISH_IMAGE,
        category: 'drink',
        tags: ['non-alcoholic', 'spicy'],
      },
      {
        name: 'Яблочный штрудель',
        description: 'Тонкое тесто, печёные яблоки, корица и ванильный соус. Бабушка трактирщика была бы довольна.',
        price: 340,
        image: DISH_IMAGE,
        category: 'dessert',
        tags: ['sweet', 'popular'],
      },
      {
        name: 'Шоколадный фондан "Лава вулкана"',
        description: 'Горячий кекс с жидкой шоколадной серединой и шариком сливочного мороженого.',
        price: 420,
        image: DISH_IMAGE,
        category: 'dessert',
        tags: ['sweet'],
      },
      {
        name: 'Сырная доска искателя приключений',
        description: 'Пять сортов сыра, орехи, мёд и виноград. Идеально под эль или вино.',
        price: 560,
        image: DISH_IMAGE,
        category: 'food',
        tags: ['popular'],
      },
      {
        name: 'Зелье "Утро после"',
        description: 'Рассол на основе огуречного отвара с укропом и чесноком. Спасает после бурной ночи в таверне.',
        price: 100,
        image: DISH_IMAGE,
        category: 'drink',
        tags: ['non-alcoholic', 'restorative'],
      },
      {
        name: 'Мороженое "Проклятие лича"',
        description: 'Чёрное кунжутное мороженое с крошкой из печенья. Выглядит зловеще, на вкус — божественно.',
        price: 300,
        image: DISH_IMAGE,
        category: 'dessert',
        tags: ['sweet', 'exotic'],
      },
      {
        name: 'Огненный суп из Преисподней',
        description: 'Том-ям с креветками, кокосовым молоком и таким количеством перца, что дракон поперхнётся.',
        price: 580,
        image: DISH_IMAGE,
        category: 'food',
        tags: ['spicy', 'exotic', 'fish'],
      },
      {
        name: 'Печенье судьбы',
        description: 'Хрустящее печенье с предсказанием внутри. Все пророчества — от местного барда, не воспринимайте всерьёз.',
        price: 180,
        image: DISH_IMAGE,
        category: 'dessert',
        tags: ['sweet', 'exotic'],
      },
    ],
  })
}

main()