import { prisma } from '../src/db/prisma.js'

const DISH_IMAGE = '/images/dishes/BWE1_0015_rune-stone-button-circle.png'

async function main() {
  await prisma.category.createMany({
    data: [
      { slug: 'food', nameRu: 'Еда', nameEn: 'Food' },
      { slug: 'drink', nameRu: 'Напитки', nameEn: 'Drinks' },
      { slug: 'dessert', nameRu: 'Десерты', nameEn: 'Desserts' },
    ],
  })

  await prisma.tag.createMany({
    data: [
      { slug: 'spicy', nameRu: 'Острое', nameEn: 'Spicy' },
      { slug: 'hot', nameRu: 'Горячее', nameEn: 'Hot' },
      { slug: 'meat', nameRu: 'Мясо', nameEn: 'Meat' },
      { slug: 'vegetarian', nameRu: 'Вегетарианское', nameEn: 'Vegetarian' },
      { slug: 'sweet', nameRu: 'Сладкое', nameEn: 'Sweet' },
      { slug: 'alcohol', nameRu: 'Алкоголь', nameEn: 'Alcohol' },
      { slug: 'non-alcoholic', nameRu: 'Безалкогольное', nameEn: 'Non-alcoholic' }
    ],
  })

  await prisma.allergen.createMany({
    data: [
      { slug: 'gluten', nameRu: 'Глютен', nameEn: 'Gluten' },
      { slug: 'lactose', nameRu: 'Лактоза', nameEn: 'Lactose' },
      { slug: 'eggs', nameRu: 'Яйца', nameEn: 'Eggs' },
      { slug: 'fish', nameRu: 'Рыба', nameEn: 'Fish' },
      { slug: 'shellfish', nameRu: 'Ракообразные', nameEn: 'Shellfish' },
      { slug: 'molluscs', nameRu: 'Моллюски', nameEn: 'Molluscs' },
      { slug: 'peanuts', nameRu: 'Арахис', nameEn: 'Peanuts' },
      { slug: 'nuts', nameRu: 'Орехи (древесные)', nameEn: 'Tree Nuts' },
      { slug: 'soy', nameRu: 'Соя', nameEn: 'Soy' },
      { slug: 'sesame', nameRu: 'Кунжут', nameEn: 'Sesame' },
      { slug: 'celery', nameRu: 'Сельдерей', nameEn: 'Celery' },
      { slug: 'mustard', nameRu: 'Горчица', nameEn: 'Mustard' },
      { slug: 'sulphites', nameRu: 'Сульфиты (E220-228)',  nameEn: 'Sulphites' },
      { slug: 'lupin', nameRu: 'Люпин', nameEn: 'Lupin' },
    ],
  })

  const dishes = [
    {
      nameRu: 'Кровавый пир Весимира',
      nameEn: "Vesemir's Bloody Feast",
      descriptionRu: 'Тартар из говядины с маринованным луком, желтком перепелиного яйца и каперсами. Подаётся с гренками из ржаного хлеба.',
      descriptionEn: 'Beef tartare with pickled onion, quail egg yolk and capers. Served with rye croutons.',
      price: 590,
      categorySlug: 'food',
      tagSlugs: ['meat'],
      allergenSlugs: ['gluten', 'eggs', 'mustard'],
    },
    {
      nameRu: 'Клыки волколака',
      nameEn: "Werewolf's Fangs",
      descriptionRu: 'Карпаччо из говяжьей вырезки с пармезаном, кедровыми орехами и рукколой. Заправка — оливковое масло и сок лимона.',
      descriptionEn: 'Beef tenderloin carpaccio with parmesan, pine nuts and arugula. Dressed with olive oil and lemon juice.',
      price: 580,
      categorySlug: 'food',
      tagSlugs: ['meat'],
      allergenSlugs: ['lactose', 'nuts'],
    },
    {
      nameRu: 'Гномьи соленья',
      nameEn: "Dwarf's Pickles",
      descriptionRu: 'Ассорти из маринованных огурцов, помидоров черри, грибов и хрустящего репчатого лука с пряными травами.',
      descriptionEn: 'Assorted pickled cucumbers, cherry tomatoes, mushrooms and crispy onions with herbs.',
      price: 280,
      categorySlug: 'food',
      tagSlugs: ['vegetarian', 'spicy'],
      allergenSlugs: ['mustard', 'sulphites'],
    },
    {
      nameRu: 'Свиток некроманта',
      nameEn: "Necromancer's Scroll",
      descriptionRu: 'Тонкий лаваш с ростбифом, вялеными томатами, руколой и пармезаном. Свернут в плотный рулет.',
      descriptionEn: 'Thin lavash with roast beef, sun-dried tomatoes, arugula and parmesan. Rolled into a tight roll.',
      price: 420,
      categorySlug: 'food',
      tagSlugs: ['meat'],
      allergenSlugs: ['gluten', 'lactose'],
    },
    {
      nameRu: 'Логово тролля',
      nameEn: "Troll's Lair",
      descriptionRu: 'Закуска из копчёного лосося с творожным сыром, каперсами и укропом на ржаном хлебе.',
      descriptionEn: 'Smoked salmon with cream cheese, capers and dill on rye bread.',
      price: 450,
      categorySlug: 'food',
      tagSlugs: ['meat'],
      allergenSlugs: ['gluten', 'lactose', 'fish'],
    },
    {
      nameRu: 'Тарелка друида',
      nameEn: "Druid's Plate",
      descriptionRu: 'Нарезка из маринованных овощей: артишоки, кабачки, перец, маслины с пряными травами.',
      descriptionEn: 'Marinated vegetables selection: artichokes, zucchini, peppers, olives with herbs.',
      price: 300,
      categorySlug: 'food',
      tagSlugs: ['vegetarian'],
      allergenSlugs: ['sulphites'],
    },
    {
      nameRu: 'Зельеварня алхимика',
      nameEn: "Alchemist's Pantry",
      descriptionRu: 'Тарелка с ферментированными овощами: кимчи из пекинской капусты, квашеный перец, маринованный редис и кабачки с пряностями.',
      descriptionEn: 'Plate with fermented vegetables: kimchi, pickled peppers, fermented radish and zucchini with spices.',
      price: 290,
      categorySlug: 'food',
      tagSlugs: ['vegetarian', 'spicy'],
      allergenSlugs: ['gluten', 'sulphites'],
    },
    {
      nameRu: 'Мясо на костре',
      nameEn: 'Tavern Cured Meats',
      descriptionRu: 'Традиционная закуска из вяленого мяса: свиная брезаола, говяжья прошутто и пикантное салями с травами.',
      descriptionEn: 'Traditional selection of cured meats: pork bresaola, beef prosciutto and spicy salami with herbs.',
      price: 490,
      categorySlug: 'food',
      tagSlugs: ['meat', 'spicy'],
      allergenSlugs: ['gluten'],
    },
    {
      nameRu: 'Крылья василиска',
      nameEn: "Basilisk's Wings",
      descriptionRu: 'Острые куриные крылья в соусе из перца чили и томатов. Подаются с сельдереем и голубым сырным соусом.',
      descriptionEn: 'Spicy chicken wings in chilli-tomato sauce. Served with celery and blue cheese dip.',
      price: 460,
      categorySlug: 'food',
      tagSlugs: ['meat', 'spicy'],
      allergenSlugs: ['lactose', 'celery'],
    },
    {
      nameRu: 'Котёл ведьмака',
      nameEn: "Witcher's Cauldron",
      descriptionRu: 'Густое рагу из дикого кабана с чёрным пивом, травами, грибами и сушёной клюквой. Подаётся с хрустящим хлебом.',
      descriptionEn: 'Thick wild boar stew with dark beer, herbs, mushrooms and dried cranberries. Served with crusty bread.',
      price: 750,
      categorySlug: 'food',
      tagSlugs: ['hot', 'meat'],
      allergenSlugs: ['gluten', 'sulphites'],
    },
    {
      nameRu: 'Тушёный варг',
      nameEn: 'Braised Warg',
      descriptionRu: 'Медленно тушёная баранья нога с розмарином, чесноком и пряными кореньями. Подаётся с картофельным пюре и печёным чесноком.',
      descriptionEn: 'Slow braised lamb leg with rosemary, garlic and spiced roots. Served with mashed potatoes and roasted garlic.',
      price: 890,
      categorySlug: 'food',
      tagSlugs: ['hot', 'meat'],
      allergenSlugs: ['lactose'],
    },
    {
      nameRu: 'Огонь Смауга',
      nameEn: "Smaug's Fire",
      descriptionRu: 'Стейк из говяжьей вырезки с острым перцем чили, чесноком и сливочным маслом. Подаётся с запечённым картофелем и травяным маслом.',
      descriptionEn: 'Beef tenderloin steak with chilli peppers, garlic and butter. Served with baked potato and herb butter.',
      price: 1290,
      categorySlug: 'food',
      tagSlugs: ['hot', 'meat', 'spicy'],
      allergenSlugs: ['lactose'],
    },
    {
      nameRu: 'Подземелье гномов',
      nameEn: "Dwarf's Dungeon Stew",
      descriptionRu: 'Гуляш из говядины с паприкой, томатами и болгарским перцем. Подаётся с галушками из картофельной муки и сметаной.',
      descriptionEn: 'Beef goulash with paprika, tomatoes and peppers. Served with potato dumplings and sour cream.',
      price: 650,
      categorySlug: 'food',
      tagSlugs: ['hot', 'meat', 'spicy'],
      allergenSlugs: ['gluten', 'lactose'],
    },
    {
      nameRu: 'Сердце дракона',
      nameEn: "Dragon's Heart",
      descriptionRu: 'Говяжье сердце, фаршированное шампиньонами и травами, запечённое в сливочном соусе с паприкой. Подаётся с печёным картофелем.',
      descriptionEn: 'Beef heart stuffed with mushrooms and herbs, baked in cream sauce with paprika. Served with baked potatoes.',
      price: 680,
      categorySlug: 'food',
      tagSlugs: ['hot', 'meat'],
      allergenSlugs: ['lactose'],
    },
    {
      nameRu: 'Чёрный гримуар',
      nameEn: 'Black Grimoire Pasta',
      descriptionRu: 'Паста из чёрного риса с кальмарами, чернилами каракатицы, чесноком и пряными травами. Подаётся с томатами черри и зеленью.',
      descriptionEn: 'Black rice pasta with squid, squid ink, garlic and herbs. Served with cherry tomatoes and fresh greens.',
      price: 720,
      categorySlug: 'food',
      tagSlugs: ['hot'],
      allergenSlugs: ['gluten', 'molluscs'],
    },
    {
      nameRu: 'Стейк из Каэр Морхена',
      nameEn: 'Kaer Morhen Steak',
      descriptionRu: 'Стейк из мраморной говядины с розмариново-чесночным маслом, карамелизированным луком и жареным чесноком.',
      descriptionEn: 'Marbled beef steak with rosemary-garlic butter, caramelized onion and roasted garlic.',
      price: 1490,
      categorySlug: 'food',
      tagSlugs: ['hot', 'meat'],
      allergenSlugs: ['lactose'],
    },
    {
      nameRu: 'Ужин некроманта',
      nameEn: "Necromancer's Roast",
      descriptionRu: 'Свиная корейка, медленно запечённая в пряном соусе с копчёной паприкой, мёдом и горчицей. Подаётся с квашеной капустой и пюре.',
      descriptionEn: 'Slow roasted pork loin in spicy sauce with smoked paprika, honey and mustard. Served with sauerkraut and mash.',
      price: 740,
      categorySlug: 'food',
      tagSlugs: ['hot', 'meat', 'sweet'],
      allergenSlugs: ['mustard', 'sulphites'],
    },
    {
      nameRu: 'Священный огонь паладина',
      nameEn: "Paladin's Sacred Fire",
      descriptionRu: 'Овощи на гриле: кабачки, баклажаны, сладкий перец, красный лук и томаты. Подаются с соусом песто и козьим сыром.',
      descriptionEn: 'Grilled vegetables: zucchini, eggplant, peppers, red onion and tomatoes. Served with pesto sauce and goat cheese.',
      price: 520,
      categorySlug: 'food',
      tagSlugs: ['hot', 'vegetarian'],
      allergenSlugs: ['lactose', 'nuts'],
    },
    {
      nameRu: 'Копьё легионера',
      nameEn: "Legionnaire's Spear Ribs",
      descriptionRu: 'Свиные ребрышки в медово-чили маринаде с чесноком. Запекаются до хрустящей корочки. Подаются с картофелем фри.',
      descriptionEn: 'Pork ribs in honey-chilli-garlic marinade. Baked to crispy perfection. Served with french fries.',
      price: 780,
      categorySlug: 'food',
      tagSlugs: ['hot', 'meat', 'spicy', 'sweet'],
      allergenSlugs: ['gluten', 'sulphites'],
    },
    {
      nameRu: 'Судак «Белый орёл»',
      nameEn: 'Oxenfurt Fried Fish',
      descriptionRu: 'Филе судака в хрустящей панировке с чесночным маслом — фирменное блюдо трактира «Белый орёл». Подаётся с картофельным пюре и лимоном.',
      descriptionEn: 'Crispy breaded pike-perch fillet with garlic butter, served with mashed potatoes and lemon.',
      price: 830,
      categorySlug: 'food',
      tagSlugs: ['hot'],
      allergenSlugs: ['fish', 'gluten', 'lactose', 'eggs'],
    },
    {
      nameRu: 'Пиршество вампира',
      nameEn: "Vampire's Feast",
      descriptionRu: 'Телятина, тушёная в красном вине с луком, морковью, грибами и беконом. Подаётся с картофельным пюре с хреном.',
      descriptionEn: 'Veal braised in red wine with onions, carrots, mushrooms and bacon. Served with horseradish mashed potatoes.',
      price: 850,
      categorySlug: 'food',
      tagSlugs: ['hot', 'meat'],
      allergenSlugs: ['lactose', 'sulphites'],
    },
    {
      nameRu: 'Молот паладина',
      nameEn: "Paladin's Warhammer Chop",
      descriptionRu: 'Телячья отбивная на кости с пряным маслом и чесноком. Подаётся с жареной картошкой и свежим салатом.',
      descriptionEn: 'Veal chop on the bone with herb butter and garlic. Served with fried potatoes and fresh salad.',
      price: 920,
      categorySlug: 'food',
      tagSlugs: ['hot', 'meat'],
      allergenSlugs: ['lactose'],
    },
    {
      nameRu: 'Паэлья Подземелья',
      nameEn: 'Underdark Paella',
      descriptionRu: 'Чёрная паэлья с кальмарами, мидиями, креветками и курицей на рисе с чернилами каракатицы и пряными травами.',
      descriptionEn: 'Black paella with squid, mussels, prawns and chicken, made with squid ink rice and herbs.',
      price: 980,
      categorySlug: 'food',
      tagSlugs: ['hot', 'meat', 'spicy'],
      allergenSlugs: ['shellfish', 'molluscs', 'gluten'],
    },
    {
      nameRu: 'Медовый торт Махакама',
      nameEn: 'Mahakam Honey Cake',
      descriptionRu: 'Многослойный медовый торт с грецкими орехами и сметанным кремом. Классика гномьих пиршеств.',
      descriptionEn: 'Layered honey cake with walnuts and sour cream frosting. A classic of dwarven feasts.',
      price: 420,
      categorySlug: 'dessert',
      tagSlugs: ['sweet', 'vegetarian'],
      allergenSlugs: ['gluten', 'lactose', 'eggs', 'nuts'],
    },
    {
      nameRu: 'Пряники Скеллиге',
      nameEn: 'Skellige Gingerbread',
      descriptionRu: 'Ароматные скеллигские пряники с мёдом, имбирём и глазурью из белого шоколада.',
      descriptionEn: 'Aromatic Skellige gingerbread with honey, ginger and white chocolate glaze.',
      price: 320,
      categorySlug: 'dessert',
      tagSlugs: ['sweet', 'vegetarian'],
      allergenSlugs: ['gluten', 'lactose', 'eggs'],
    },
    {
      nameRu: 'Штрудель Трисс',
      nameEn: "Triss Merigold's Apple Strudel",
      descriptionRu: 'Яблочный штрудель с корицей, изюмом и миндальными лепестками. Подаётся с ванильным соусом.',
      descriptionEn: 'Apple strudel with cinnamon, raisins and almond flakes. Served with vanilla sauce.',
      price: 390,
      categorySlug: 'dessert',
      tagSlugs: ['sweet', 'vegetarian'],
      allergenSlugs: ['gluten', 'lactose', 'eggs', 'nuts'],
    },
    {
      nameRu: 'Торт сирени и крыжовника',
      nameEn: "Yennefer's Lilac & Gooseberry Tart",
      descriptionRu: 'Нежный чизкейк с крыжовником, лепестками сирени и лимонной цедрой на песочной основе.',
      descriptionEn: 'Delicate cheesecake with gooseberries, lilac petals and lemon zest on a shortcrust base.',
      price: 450,
      categorySlug: 'dessert',
      tagSlugs: ['sweet', 'vegetarian'],
      allergenSlugs: ['gluten', 'lactose', 'eggs'],
    },
    {
      nameRu: 'Пирог добрых ягод',
      nameEn: 'Goodberry Pie',
      descriptionRu: 'Открытый пирог с лесными ягодами, мёдом и тимьяном. Согревает душу и тело, словно заклинание друида.',
      descriptionEn: 'Open-faced forest berry pie with honey and thyme. Warms body and soul like a druidic spell.',
      price: 360,
      categorySlug: 'dessert',
      tagSlugs: ['sweet', 'vegetarian'],
      allergenSlugs: ['gluten', 'lactose', 'eggs'],
    },
    {
      nameRu: 'Пудинг второго завтрака',
      nameEn: "Halfling's Second Breakfast Pudding",
      descriptionRu: 'Кремовый рисовый пудинг с ванилью, корицей и карамельным соусом. Подаётся тёплым.',
      descriptionEn: 'Creamy rice pudding with vanilla, cinnamon and caramel sauce. Served warm.',
      price: 310,
      categorySlug: 'dessert',
      tagSlugs: ['sweet', 'vegetarian'],
      allergenSlugs: ['lactose', 'eggs'],
    },
    {
      nameRu: 'Сокровище дракона',
      nameEn: "Dragon's Hoard Custard",
      descriptionRu: 'Золотистый ванильный крем с карамелью, хрустящим миндалём и листовым золотом.',
      descriptionEn: 'Golden vanilla custard with caramel, crunchy almonds and edible gold leaf.',
      price: 480,
      categorySlug: 'dessert',
      tagSlugs: ['sweet', 'vegetarian'],
      allergenSlugs: ['lactose', 'eggs', 'nuts'],
    },
    {
      nameRu: 'Чизкейк Лунного колодца',
      nameEn: 'Moonwell Cheesecake',
      descriptionRu: 'Эльфийский чизкейк с белым шоколадом, малиной и мятой на основе из орехового печенья.',
      descriptionEn: 'Elven cheesecake with white chocolate, raspberries and mint on a nut cookie base.',
      price: 440,
      categorySlug: 'dessert',
      tagSlugs: ['sweet', 'vegetarian'],
      allergenSlugs: ['gluten', 'lactose', 'eggs', 'nuts'],
    },
    {
      nameRu: 'Шоколад Нильфгаарда',
      nameEn: 'Nilfgaardian Dark Chocolate Soufflé',
      descriptionRu: 'Тёплый шоколадный суфле с жидкой серединкой, подаётся с мороженым из чёрной смородины.',
      descriptionEn: 'Warm dark chocolate soufflé with a molten centre, served with blackcurrant ice cream.',
      price: 510,
      categorySlug: 'dessert',
      tagSlugs: ['sweet', 'vegetarian'],
      allergenSlugs: ['gluten', 'lactose', 'eggs'],
    },
    {
      nameRu: 'Ореховая карамель гномов',
      nameEn: 'Dwarven Nut Brittle',
      descriptionRu: 'Хрустящая карамель с грецкими орехами, миндалём и морской солью. Идеальна к элю.',
      descriptionEn: 'Crunchy caramel with walnuts, almonds and sea salt. Perfect with ale.',
      price: 280,
      categorySlug: 'dessert',
      tagSlugs: ['sweet', 'vegetarian'],
      allergenSlugs: ['nuts'],
    },
    {
      nameRu: 'Зелье ведьмы',
      nameEn: "Witch's Potion",
      descriptionRu: 'Освежающий лимонад на основе сиропа бузины, лайма, мяты и содовой. Подаётся со льдом и веточкой розмарина.',
      descriptionEn: 'Refreshing elderflower lemonade with lime, mint and soda. Served with ice and rosemary sprig.',
      price: 280,
      categorySlug: 'drink',
      tagSlugs: ['non-alcoholic'],
      allergenSlugs: [],
    },
    {
      nameRu: 'Медовуха Махакама',
      nameEn: 'Mahakam Mead',
      descriptionRu: 'Домашняя медовуха с корицей, гвоздикой и апельсиновой цедрой. Подаётся горячей или холодной.',
      descriptionEn: 'Homemade mead with cinnamon, cloves and orange zest. Served hot or cold.',
      price: 320,
      categorySlug: 'drink',
      tagSlugs: ['alcohol', 'sweet'],
      allergenSlugs: ['sulphites'],
    },
    {
      nameRu: 'Слёзы эльфа',
      nameEn: "Elven Tears",
      descriptionRu: 'Просекко с добавлением сиропа из бузины и ягод годжи. Игристое, освежающее, с ягодным ароматом.',
      descriptionEn: 'Prosecco with elderflower syrup and goji berries. Sparkling and refreshing with berry aroma.',
      price: 450,
      categorySlug: 'drink',
      tagSlugs: ['alcohol'],
      allergenSlugs: ['sulphites'],
    },
    {
      nameRu: 'Кровь нечисти',
      nameEn: "Fiend's Blood",
      descriptionRu: 'Коктейль на основе виски, вишнёвого ликёра, гранатового сока и пряных биттеров. Крепкий, терпкий и тёмный.',
      descriptionEn: 'Cocktail with whisky, cherry liqueur, pomegranate juice and spiced bitters. Strong, tart and dark.',
      price: 550,
      categorySlug: 'drink',
      tagSlugs: ['alcohol', 'spicy'],
      allergenSlugs: ['sulphites'],
    },
    {
      nameRu: 'Белая ведьма',
      nameEn: 'White Witch',
      descriptionRu: 'Коктейль на основе белого рома, кокосового молока, лайма и ванильного сиропа. Нежный, сладкий, тропический.',
      descriptionEn: 'Cocktail with white rum, coconut milk, lime and vanilla syrup. Smooth, sweet and tropical.',
      price: 480,
      categorySlug: 'drink',
      tagSlugs: ['alcohol', 'sweet'],
      allergenSlugs: ['lactose', 'sulphites'],
    },
    {
      nameRu: 'Чёрная магия',
      nameEn: 'Black Magic',
      descriptionRu: 'Коктейль из водки, активированного угля, сиропа из чёрной смородины и сока лайма. Сервируется со свежими ягодами.',
      descriptionEn: 'Cocktail with vodka, activated charcoal, blackcurrant syrup and lime juice. Served with fresh berries.',
      price: 500,
      categorySlug: 'drink',
      tagSlugs: ['alcohol'],
      allergenSlugs: ['sulphites'],
    },
    {
      nameRu: 'Взгляд ледяного дракона',
      nameEn: "White Dragon's Gaze",
      descriptionRu: 'Мятно-лимонный чайный коктейль с добавлением водки, мёда и имбиря. Освежающий и согревающий одновременно.',
      descriptionEn: 'Mint-lemon tea cocktail with vodka, honey and ginger. Refreshing and warming at the same time.',
      price: 420,
      categorySlug: 'drink',
      tagSlugs: ['alcohol', 'sweet'],
      allergenSlugs: ['sulphites'],
    },
    {
      nameRu: 'Нектар мантикоры',
      nameEn: "Manticore's Nectar",
      descriptionRu: 'Свежевыжатый апельсиновый сок с добавлением манго, имбиря и пряных трав. Бодрящий и яркий.',
      descriptionEn: 'Freshly squeezed orange juice with mango, ginger and spices. Invigorating and bright.',
      price: 290,
      categorySlug: 'drink',
      tagSlugs: ['non-alcoholic'],
      allergenSlugs: [],
    },
    {
      nameRu: 'Фейерверк',
      nameEn: 'Fireworks',
      descriptionRu: 'Коктейль из джина, лимонного сока, сиропа лайма и содовой с добавлением съедобного блеска. Подаётся со слайсами цитрусовых.',
      descriptionEn: 'Cocktail with gin, lemon juice, lime syrup and soda with edible glitter. Served with citrus slices.',
      price: 530,
      categorySlug: 'drink',
      tagSlugs: ['alcohol'],
      allergenSlugs: ['sulphites'],
    },
    {
      nameRu: 'Лунный свет',
      nameEn: 'Moonlight',
      descriptionRu: 'Горячий шоколад на кокосовом молоке с корицей, ванилью и щепоткой перца чили. Подаётся с маршмеллоу.',
      descriptionEn: 'Hot chocolate with coconut milk, cinnamon, vanilla and a pinch of chilli. Served with marshmallows.',
      price: 350,
      categorySlug: 'drink',
      tagSlugs: ['non-alcoholic', 'sweet', 'spicy'],
      allergenSlugs: ['lactose'],
    },
  ]

  for (const d of dishes) {
    await prisma.dish.create({
      data: {
        nameRu: d.nameRu,
        nameEn: d.nameEn,
        descriptionRu: d.descriptionRu,
        descriptionEn: d.descriptionEn,
        price: d.price,
        images: [DISH_IMAGE],
        category: { connect: { slug: d.categorySlug } },
        tags: { connect: d.tagSlugs.map((slug) => ({ slug })) },
        allergens: { connect: d.allergenSlugs.map((slug) => ({ slug })) },
      },
    })
  }
}

const zones = [
  { slug: 'tavern', nameRu: 'Таверна', nameEn: 'Tavern', pricePerHour: 300 },
  { slug: 'vip', nameRu: 'Чертог', nameEn: 'Great Hall', pricePerHour: 800 },
  { slug: 'terrace', nameRu: 'Двор', nameEn: 'Courtyard', pricePerHour: 500 },
]

for (const z of zones) {
  await prisma.zone.create({ data: z })
}

const tavern = await prisma.zone.findUniqueOrThrow({ where: { slug: 'tavern' } })
const vip = await prisma.zone.findUniqueOrThrow({ where: { slug: 'vip' } })
const terrace = await prisma.zone.findUniqueOrThrow({ where: { slug: 'terrace' } })

const tables = [
  { number: 1, zoneId: tavern.id, capacity: 2, x: 15, y: 20 },
  { number: 2, zoneId: tavern.id, capacity: 4, x: 35, y: 20 },
  { number: 3, zoneId: tavern.id, capacity: 4, x: 55, y: 25 },
  { number: 4, zoneId: tavern.id, capacity: 6, x: 25, y: 50 },
  { number: 5, zoneId: vip.id, capacity: 4, x: 75, y: 25 },
  { number: 6, zoneId: vip.id, capacity: 8, x: 80, y: 55 },
  { number: 7, zoneId: terrace.id, capacity: 2, x: 20, y: 80 },
  { number: 8, zoneId: terrace.id, capacity: 4, x: 45, y: 82 },
]

for (const t of tables) {
  await prisma.table.create({ data: t })
}

main()
  .then(() => console.log('Seed completed'))
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
